version: "3.9"

services:
  db:
    image: postgres:17
    container_name: iris-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: iris-api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./mlruns:/app/mlruns  # ✅ 显式挂载 MLflow 日志
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-ui
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns   # ✅ 显式挂载和 api 共用的日志目录
    command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "/mlflow/mlruns"]

volumes:
  pgdata:
